# Generated by Django 5.1.2 on 2024-12-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='flagUrl',
            new_name='flag_url',
        ),
    ]
